server:
  port: 8081


swagger:
  switch: true

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: redis-bill
    jedis:
      pool:
        max-idle: 8
        max-active: 8
        max-wait: 1
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: mysql
    testWhileIdle: true
    validationQuery: SELECT 1